spring.application.name: search-injector

log.level: debug
log.max-files: 21
log.file-size: 100MB
log.path: Logs/${spring.application.name}

server:
  port: 9006

socket:
  hostname: "localhost"
  port: 9600

rabbitmq.host: 10.128.57.121
rabbitmq.exchange: ic-call-data
rabbitmq.username: test
rabbitmq.password: test
rabbitmq.routing.key: segment.stop
