spring.application.name: search-injector

log.level: debug
log.max-files: 21
log.file-size: 100MB
log.path: Logs/${spring.application.name}

server:
  port: 9006

socket:
  hostname: "localhost"
  port: 9600

#rabbitmq.host: 10.128.57.121
#rabbitmq.username: "nice-rw"
#rabbitmq.password: "nicecti1!"
rabbitmq.host: "localhost"
rabbitmq.username: "nice"
rabbitmq.password: "nice."
rabbitmq.queue-name: "ic-event-indexer"
rabbitmq.exchange: "ic-call-data"
rabbitmq.routing.key: "segment.stop"
