spring.application.name: search-injector

log.level: debug
log.max-files: 21
log.file-size: 20MB
log.path: Logs/${spring.application.name}

server:
  port: 9006

socket:
  hostname: "localhost"
  port: 9600

rabbitmq.host: localhost
rabbitmq.exchange: test1
rabbitmq.username: test
rabbitmq.password: test